// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvRsZ2TFpeKx_6u8W06tiZJjZFLTFwFY',
    appId: '1:1086990656025:web:8b2bbc8506af5b670c4088',
    messagingSenderId: '1086990656025',
    projectId: 'h-y-d-r-a-e4874',
    authDomain: 'h-y-d-r-a-e4874.firebaseapp.com',
    storageBucket: 'h-y-d-r-a-e4874.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIw0VAeBD4KGd0YJaCtq7LX7k27BMlIEQ',
    appId: '1:1086990656025:android:9061f2de41c4c5950c4088',
    messagingSenderId: '1086990656025',
    projectId: 'h-y-d-r-a-e4874',
    storageBucket: 'h-y-d-r-a-e4874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1VmySzFCpx7Jip8F7MnjrRMuNVz6eGg',
    appId: '1:1086990656025:ios:714b77f1dd80faa90c4088',
    messagingSenderId: '1086990656025',
    projectId: 'h-y-d-r-a-e4874',
    storageBucket: 'h-y-d-r-a-e4874.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlannerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1VmySzFCpx7Jip8F7MnjrRMuNVz6eGg',
    appId: '1:1086990656025:ios:714b77f1dd80faa90c4088',
    messagingSenderId: '1086990656025',
    projectId: 'h-y-d-r-a-e4874',
    storageBucket: 'h-y-d-r-a-e4874.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlannerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXvRsZ2TFpeKx_6u8W06tiZJjZFLTFwFY',
    appId: '1:1086990656025:web:3139d0bab96f61450c4088',
    messagingSenderId: '1086990656025',
    projectId: 'h-y-d-r-a-e4874',
    authDomain: 'h-y-d-r-a-e4874.firebaseapp.com',
    storageBucket: 'h-y-d-r-a-e4874.firebasestorage.app',
  );
}
